import { Listing, User } from '@/types';

export const sampleUsers: User[] = [
  {
    id: '1',
    name: 'Kwame Osei',
    email: 'kwame@example.com',
    phone: '0244123456',
    location: 'Accra',
    profileImage: '',
    role: 'seller',
    verified: true,
    joinDate: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Akosua Mensah',
    email: 'akosua@example.com',
    phone: '0205987654',
    location: 'Kumasi',
    profileImage: '',
    role: 'seller',
    verified: true,
    joinDate: new Date('2024-02-20'),
  },
  {
    id: '3',
    name: 'Kofi Asante',
    email: 'kofi@example.com',
    phone: '0271234567',
    location: 'Takoradi',
    profileImage: '',
    role: 'seller',
    verified: false,
    joinDate: new Date('2024-03-10'),
  },
];

export const sampleListings: Listing[] = [
  {
    id: '1',
    sellerId: '1',
    seller: sampleUsers[0],
    title: 'iPhone 13 Pro - Like New',
    description: 'Barely used iPhone 13 Pro in excellent condition. Comes with original box, charger, and case. No scratches on screen.',
    price: 4500,
    category: 'electronics',
    subcategory: 'Phones & Tablets',
    condition: 'like-new',
    images: [
      'https://images.unsplash.com/photo-1632661674596-df8be070a5c5?w=800',
      'https://images.unsplash.com/photo-1632633728024-e1fd4bef561a?w=800',
    ],
    location: 'Accra',
    status: 'active',
    views: 245,
    favorites: 18,
    createdAt: new Date('2024-11-20'),
    updatedAt: new Date('2024-11-20'),
  },
  {
    id: '2',
    sellerId: '2',
    seller: sampleUsers[1],
    title: 'Nike Air Jordan 1 Retro High',
    description: 'Authentic Nike Air Jordan 1 in great condition. Size 42. Worn only a few times. Perfect for sneaker collectors.',
    price: 850,
    category: 'shoes',
    subcategory: 'Sneakers',
    condition: 'good',
    images: [
      'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=800',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800',
    ],
    location: 'Kumasi',
    status: 'active',
    views: 156,
    favorites: 23,
    createdAt: new Date('2024-11-22'),
    updatedAt: new Date('2024-11-22'),
  },
  {
    id: '3',
    sellerId: '1',
    seller: sampleUsers[0],
    title: 'Designer Leather Jacket - Mens',
    description: 'Premium leather jacket from Zara. Size L. Gently used, no visible wear. Perfect for the harmattan season.',
    price: 320,
    category: 'clothing',
    subcategory: "Men's Clothing",
    condition: 'like-new',
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800',
    ],
    location: 'Accra',
    status: 'active',
    views: 89,
    favorites: 12,
    createdAt: new Date('2024-11-23'),
    updatedAt: new Date('2024-11-23'),
  },
  {
    id: '4',
    sellerId: '3',
    seller: sampleUsers[2],
    title: 'HP Laptop - Core i5, 8GB RAM',
    description: 'HP Pavilion laptop in good working condition. Core i5, 8GB RAM, 256GB SSD. Great for students and office work.',
    price: 1800,
    category: 'electronics',
    subcategory: 'Laptops',
    condition: 'good',
    images: [
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800',
    ],
    location: 'Takoradi',
    status: 'active',
    views: 312,
    favorites: 45,
    createdAt: new Date('2024-11-21'),
    updatedAt: new Date('2024-11-21'),
  },
  {
    id: '5',
    sellerId: '2',
    seller: sampleUsers[1],
    title: 'Kente Cloth - Traditional Wear',
    description: 'Beautiful authentic Kente cloth, handwoven. Perfect for special occasions. High quality craftsmanship.',
    price: 450,
    category: 'clothing',
    subcategory: 'Traditional Wear',
    condition: 'new',
    images: [
      'https://images.unsplash.com/photo-1617722990150-f52f6c0e68db?w=800',
    ],
    location: 'Kumasi',
    status: 'active',
    views: 178,
    favorites: 34,
    createdAt: new Date('2024-11-24'),
    updatedAt: new Date('2024-11-24'),
  },
  {
    id: '6',
    sellerId: '1',
    seller: sampleUsers[0],
    title: 'Apple Watch Series 8 - GPS',
    description: 'Apple Watch Series 8 in excellent condition. Comes with 3 different bands. Battery health 100%.',
    price: 2200,
    category: 'accessories',
    subcategory: 'Watches',
    condition: 'like-new',
    images: [
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800',
    ],
    location: 'Accra',
    status: 'active',
    views: 267,
    favorites: 56,
    createdAt: new Date('2024-11-19'),
    updatedAt: new Date('2024-11-19'),
  },
  {
    id: '7',
    sellerId: '3',
    seller: sampleUsers[2],
    title: 'Sony Headphones - Noise Cancelling',
    description: 'Sony WH-1000XM4 noise cancelling headphones. Amazing sound quality. Includes carrying case.',
    price: 780,
    category: 'electronics',
    subcategory: 'Headphones',
    condition: 'good',
    images: [
      'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800',
    ],
    location: 'Takoradi',
    status: 'active',
    views: 134,
    favorites: 28,
    createdAt: new Date('2024-11-25'),
    updatedAt: new Date('2024-11-25'),
  },
  {
    id: '8',
    sellerId: '2',
    seller: sampleUsers[1],
    title: 'Designer Handbag - Louis Vuitton Style',
    description: 'Premium quality designer handbag. Excellent condition, barely used. Perfect accessory for any outfit.',
    price: 550,
    category: 'accessories',
    subcategory: 'Bags',
    condition: 'like-new',
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800',
    ],
    location: 'Kumasi',
    status: 'active',
    views: 198,
    favorites: 41,
    createdAt: new Date('2024-11-18'),
    updatedAt: new Date('2024-11-18'),
  },
  {
    id: '9',
    sellerId: '1',
    seller: sampleUsers[0],
    title: 'Adidas Sneakers - White & Black',
    description: 'Adidas Stan Smith sneakers. Size 40. Clean and fresh. Very comfortable for daily wear.',
    price: 280,
    category: 'shoes',
    subcategory: 'Sneakers',
    condition: 'good',
    images: [
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800',
    ],
    location: 'Accra',
    status: 'active',
    views: 223,
    favorites: 37,
    createdAt: new Date('2024-11-26'),
    updatedAt: new Date('2024-11-26'),
  },
  {
    id: '10',
    sellerId: '3',
    seller: sampleUsers[2],
    title: 'Samsung Galaxy Tab S7',
    description: 'Samsung tablet in perfect condition. Great for entertainment and productivity. Includes S-Pen.',
    price: 1650,
    category: 'electronics',
    subcategory: 'Phones & Tablets',
    condition: 'like-new',
    images: [
      'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=800',
    ],
    location: 'Takoradi',
    status: 'active',
    views: 189,
    favorites: 31,
    createdAt: new Date('2024-11-17'),
    updatedAt: new Date('2024-11-17'),
  },
];
